import React from 'react';
import { FileText, X, Download, Printer, Shield, CheckCircle2, Building2, User, Car, Calendar, DollarSign } from 'lucide-react';

interface DocumentModalProps {
  isOpen: boolean;
  onClose: () => void;
  documentData: {
    policyNumber?: string;
    customerName?: string;
    vehicleNumber?: string;
    vehicleType?: string;
    insuranceCompany?: string;
    startDate?: string;
    expiryDate?: string;
    premiumAmount?: string | number;
    documentUrl?: string | null;
  } | null;
}

export const DocumentModal: React.FC<DocumentModalProps> = ({ isOpen, onClose, documentData }) => {
  if (!isOpen || !documentData) return null;

  const isBase64 = documentData.documentUrl && documentData.documentUrl.startsWith('data:');
  const isPdf = documentData.documentUrl && (documentData.documentUrl.endsWith('.pdf') || documentData.documentUrl.includes('pdf'));

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    if (documentData.documentUrl && isBase64) {
      const link = document.createElement('a');
      link.href = documentData.documentUrl;
      link.download = `Policy_${documentData.policyNumber || 'Document'}.pdf`;
      document.body.appendChild(link);
      link.click();
      link.remove();
    } else {
      // Create a printable text/HTML blob for download
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>Insurance Policy - ${documentData.policyNumber}</title>
          <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #1e293b; background: #fff; }
            .header { border-bottom: 2px solid #0284c7; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
            .title { font-size: 24px; font-weight: bold; color: #0284c7; }
            .subtitle { font-size: 14px; color: #64748b; }
            .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }
            .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; }
            .card h4 { margin: 0 0 10px 0; font-size: 14px; color: #475569; text-transform: uppercase; letter-spacing: 0.05em; }
            .field { margin-bottom: 8px; font-size: 14px; }
            .field label { font-weight: 600; color: #334155; }
            .footer { border-top: 1px solid #e2e8f0; pt: 20px; text-align: center; font-size: 12px; color: #94a3b8; }
          </style>
        </head>
        <body>
          <div class="header">
            <div>
              <div class="title">${documentData.insuranceCompany || 'Shield Insurance Platform'}</div>
              <div class="subtitle">Official Policy Certificate</div>
            </div>
            <div style="text-align: right;">
              <div style="font-weight: bold; font-size: 18px;">POL-${documentData.policyNumber || '402000600665'}</div>
              <div class="subtitle">Status: ACTIVE</div>
            </div>
          </div>

          <div class="grid">
            <div class="card">
              <h4>Customer Information</h4>
              <div class="field"><label>Customer Name:</label> ${documentData.customerName || 'Lakshmi V'}</div>
              <div class="field"><label>Vehicle Number:</label> ${documentData.vehicleNumber || 'KA42Y5782'}</div>
              <div class="field"><label>Vehicle Type:</label> ${documentData.vehicleType || 'Two Wheeler'}</div>
            </div>

            <div class="card">
              <h4>Policy Details</h4>
              <div class="field"><label>Insurance Company:</label> ${documentData.insuranceCompany || 'Zuno General Insurance Limited'}</div>
              <div class="field"><label>Policy Period:</label> ${documentData.startDate || '11/09/2025'} to ${documentData.expiryDate || '10/09/2026'}</div>
              <div class="field"><label>Total Premium:</label> ₹${documentData.premiumAmount || '1,186.67'}</div>
            </div>
          </div>

          <div class="footer">
            Generated by Shield Insurance CRM · Authorized Certificate Document
          </div>
        </body>
        </html>
      `;
      const blob = new Blob([htmlContent], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const win = window.open(url, '_blank');
      if (win) {
        win.print();
      }
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-fade-in">
      <div className="glass-card max-w-3xl w-full p-6 sm:p-8 space-y-6 border border-white/15 shadow-2xl relative animate-slide-up max-h-[90vh] overflow-y-auto">
        
        {/* Header bar */}
        <div className="flex items-center justify-between border-b border-white/10 pb-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-brand-600/20 border border-brand-600/30 flex items-center justify-center text-brand-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base font-bold text-text-primary">Policy Document Certificate</h3>
                <span className="badge badge-success text-[10px] uppercase font-bold">Verified</span>
              </div>
              <p className="text-xs text-text-muted mt-0.5">Policy Number: <span className="font-mono text-brand-400 font-bold">{documentData.policyNumber || '402000600665'}</span></p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleDownload}
              className="btn-ghost border border-white/10 text-xs px-3 py-1.5 flex items-center gap-1.5 hover:bg-white/[0.05]"
            >
              <Download className="w-3.5 h-3.5" /> Download
            </button>
            <button
              onClick={handlePrint}
              className="btn-primary text-xs px-3.5 py-1.5 flex items-center gap-1.5 shadow-lg shadow-brand-600/20"
            >
              <Printer className="w-3.5 h-3.5" /> Print / View
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-xl text-text-subtle hover:text-text-primary hover:bg-white/[0.06] transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Embedded Base64 PDF / Image or Structured Certificate */}
        {isBase64 ? (
          <div className="w-full h-[550px] rounded-xl overflow-hidden border border-white/10 bg-black/40">
            {documentData.documentUrl?.startsWith('data:image/') ? (
              <img src={documentData.documentUrl} alt="Policy Document" className="w-full h-full object-contain" />
            ) : (
              <iframe
                src={documentData.documentUrl || ''}
                title="Policy Document PDF"
                className="w-full h-full border-0"
              />
            )}
          </div>
        ) : (
          <div className="p-6 rounded-2xl bg-white/[0.02] border border-white/[0.06] space-y-6">
            
            <div className="flex items-center justify-between p-4 rounded-xl bg-brand-600/10 border border-brand-600/20">
              <div className="flex items-center gap-3">
                <Shield className="w-6 h-6 text-brand-400" />
                <div>
                  <h4 className="text-sm font-bold text-text-primary">{documentData.insuranceCompany || 'Zuno General Insurance Limited'}</h4>
                  <p className="text-xs text-text-muted">Official Policy Certificate & Coverage Schedule</p>
                </div>
              </div>
              <CheckCircle2 className="w-5 h-5 text-success" />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="p-4 rounded-xl bg-white/[0.02] border border-white/[0.04] space-y-3">
                <h5 className="text-2xs uppercase tracking-widest font-bold text-brand-400">Customer & Vehicle Details</h5>
                <div className="space-y-2 text-xs">
                  <div className="flex items-center justify-between">
                    <span className="text-text-subtle flex items-center gap-1.5"><User className="w-3.5 h-3.5" /> Customer Name:</span>
                    <span className="font-bold text-text-primary">{documentData.customerName || 'Lakshmi V'}</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-text-subtle flex items-center gap-1.5"><Car className="w-3.5 h-3.5" /> Vehicle Number:</span>
                    <span className="font-bold font-mono text-brand-400">{documentData.vehicleNumber || 'KA42Y5782'}</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-text-subtle">Vehicle Type:</span>
                    <span className="font-semibold text-text-muted capitalize">{documentData.vehicleType || 'Two Wheeler'}</span>
                  </div>
                </div>
              </div>

              <div className="p-4 rounded-xl bg-white/[0.02] border border-white/[0.04] space-y-3">
                <h5 className="text-2xs uppercase tracking-widest font-bold text-brand-400">Policy Terms & Premium</h5>
                <div className="space-y-2 text-xs">
                  <div className="flex items-center justify-between">
                    <span className="text-text-subtle flex items-center gap-1.5"><Calendar className="w-3.5 h-3.5" /> Start Date:</span>
                    <span className="font-semibold text-text-muted">{documentData.startDate ? new Date(documentData.startDate).toLocaleDateString() : '11/09/2025'}</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-text-subtle flex items-center gap-1.5"><Calendar className="w-3.5 h-3.5" /> Expiry Date:</span>
                    <span className="font-bold text-success">{documentData.expiryDate ? new Date(documentData.expiryDate).toLocaleDateString() : '10/09/2026'}</span>
                  </div>
                  <div className="flex items-center justify-between pt-1 border-t border-white/[0.06]">
                    <span className="text-text-subtle flex items-center gap-1.5"><DollarSign className="w-3.5 h-3.5" /> Premium Amount:</span>
                    <span className="font-bold text-text-primary">₹{documentData.premiumAmount || '1,186.67'}</span>
                  </div>
                </div>
              </div>
            </div>

            <div className="p-4 rounded-xl bg-white/[0.02] border border-dashed border-white/10 text-center">
              <p className="text-xs text-text-muted">
                📄 Digital copy stored securely. Click <span className="text-brand-400 font-semibold cursor-pointer" onClick={handlePrint}>Print / View</span> to generate a full printable PDF document statement.
              </p>
            </div>

          </div>
        )}

      </div>
    </div>
  );
};
